### ISSUE TITLE
find row by other value

### ISSUE THREAD

**Issue by stellanhaglund** [sdd-org/kiddo#10]
Hello, nice work with the crate!

I was thinking of using this as part of a similar image search setup, but for that to make sense I need a way to find/delete/update rows in the tree in other ways than using the embeddings from the images to find them. 

Do you have any suggestions for that?

**Comment by sdd** [comment]
Hi Stellan - thanks! 

Which version are you using for this: the v2 beta, or the older 0.2.x branch?

**Comment by sdd** [comment]
Closing this due to lack of response.
