### ISSUE TITLE
KdTree::with_capacity(0) panics

### ISSUE THREAD

**Issue by abey79** [sdd-org/kiddo#11]
This is due to the use of `ilog2`. Likely fixed by adding a `.max(1)` on the argument.

**Comment by sdd** [comment]
Thanks for reporting! I'll update in the next release over the next couple of days 👍🏼

**Comment by sdd** [comment]
Figured I may as well just do it straight away, it's such an easy fix.

Released as https://crates.io/crates/kiddo/2.0.0-beta.6

Thanks again, it's really helpful to get feedback on v2 while it is still in beta! 😄
