### ISSUE TITLE
Question: Is it possible to use Kiddo with dimension unknow at compile time?

### ISSUE THREAD

**Issue by abstractqqq** [sdd-org/kiddo#111]
Hi, I am trying to rewrite a lot of statistical metrics (various entropies) and also KNN with the goal of porting them to Python. For general data science use cases, it is impossible to know how many features (dimensions) will be used to find the closest neighbors. It could be 2, 3, or 10, etc.. Would kiddo be able to support such use cases? Thank you.

A typical input would like a matrix with nrows representing the number of records, and ncols representing the features.

Such a tree can be immutable once constructed. But it is impossible to know ncols ahead of time.

**Comment by sdd** [comment]
Hi - unfortunately not, Kiddo always requires the dimensionality to be known at compile time. This is for performance - knowing the dimensionality at compile time allows arrays to be used in places where `Vec`s would otherwise be required. Sorry that it can't help with your use case! :-)
