### ISSUE TITLE
Incorrect documentation links and code for ImmutableKdTree

### ISSUE THREAD

**Issue by ozwaldorf** [sdd-org/kiddo#113]
There are some incomplete and/or copy pasted documentation for the new ImmutableKdTree.

- In the crate's top level doc comment, the link for the immutable tree is invalid
- https://docs.rs/kiddo/3.0.0/kiddo/immutable/float/kdtree/struct.ImmutableKdTree.html#method.size has some example code that uses the normal KdTree

**Comment by sdd** [comment]
Thanks for spotting this, and thanks even more for the PR. Will merge ASAP
