### ISSUE TITLE
Question: Must the number of points per input be known at compile time?

### ISSUE THREAD

**Issue by NnannaOmoke** [sdd-org/kiddo#178]
This means that you cannot build a `KdTree` from a vector of vectors/slices, which severely limits the functionality to use cases where the dimensions of the input are hard coded in.

**Comment by NnannaOmoke** [comment]
i.e. something like this would not work:
```rust
let tree = points.rows().into_iter().map(|row| row.to_vec()).collect::<Vec<Vec<f64>>>();
//assume that points is an `ndarray`
let tree = KdTree<f64, 2> = (&tree).into();
```
Even though this is a very `points` agnostic way of creating `KdTree`s

**Comment by sdd** [comment]
Unfortunately yes, Kiddo does not support creating trees whose dimensionality is not known at compile time. This is due to the use of arrays rather than Vecs for performance.
