### ISSUE TITLE
Issues with generator 0.8.0+ build on aarch64-apple-ios-sim and aarch64-apple-ios

### ISSUE THREAD

**Issue by tonylazarew** [sdd-org/kiddo#182]
Hi, just letting you know that I have found issues building generator 0.8.0+ for `ios` and `ios-sim` targets, reported here: https://github.com/Xudong-Huang/generator-rs/issues/64

This means that kiddo 4.2.1 doesn't build on these targets either.

**Comment by sdd** [comment]
Aah - thanks for the heads up, Tony. Are you blocked by this or does pinning to 4.2.0 work for you until there's an upstream fix in https://github.com/Xudong-Huang/generator-rs/issues/64?

**Comment by sdd** [comment]
Hi @tonylazarew - I'm merging in https://github.com/sdd/kiddo/pull/197 if the tests pass. I'd love to hear if this fixes the problem for you.

Scott
