### ISSUE TITLE
unresolved import `within_unsorted_iter` for `i686-unkonwn-linux`

### ISSUE THREAD

**Issue by edgarriba** [sdd-org/kiddo#190]
hi! I'm trying to deploy the library in a pipeline that needs to compile for i686 and I'm getting the following: `error[E0432]: unresolved import within_unsorted_iter`

See the full log here: https://github.com/kornia/kornia-rs/actions/runs/12305965393/job/34346689720?pr=182

Any suggestions ? thanks in advance!

**Comment by sdd** [comment]
Hi @edgarriba - I'll see what I can do for you

**Comment by sdd** [comment]
Ok, I think I have a fix for both the `error[E0432]: unresolved import within_unsorted_iter` error and the `error[E0308]: mismatched types`

**Comment by sdd** [comment]
Published as https://crates.io/crates/kiddo/5.0.2

**Comment by edgarriba** [comment]
awesome ! i got green lights in ci --  thanks so much !
