### ISSUE TITLE
Remove failure

### ISSUE THREAD

**Issue by wentasah** [sdd-org/kiddo#28]
Removal in the following code fails. Either, I'm using the crate wrong, or it's a bug.

```rust
use kiddo::KdTree;
use rand::prelude::*;
use rand_chacha::ChaCha8Rng;

fn main() {
    let mut rng = ChaCha8Rng::seed_from_u64(1);
    let entries = (0..33)
        .map(|_| [rng.gen::<f64>(), rng.gen::<f64>()])
        .collect::<Vec<_>>();
    let mut kdtree = KdTree::new();
    for (i, e) in entries.iter().enumerate() {
        println!("adding {i} {:?}", *e);
        kdtree.add(e, i);
    }
    println!("kdtree size {}", kdtree.size());
    for (i, e) in entries.iter().enumerate() {
        println!("removing {i} {:?}", *e);
        assert!(kdtree.remove(e, i) == 1);
    }
}
```
The assertion failure appears only if the size of the tree is bigger than 32.

The output of the program is:
```
adding 0 [0.40248566366484806, 0.08038370892978197]
adding 1 [0.5965601809348549, 0.2193245804838001]
adding 2 [0.28369059130373764, 0.7106102236811087]
adding 3 [0.46108817320691575, 0.15265269640601276]
adding 4 [0.8747810784358925, 0.7066240720855618]
adding 5 [0.4832571563375021, 0.5772091371337079]
adding 6 [0.09945952283110959, 0.2639175681341963]
adding 7 [0.45345972465534234, 0.28022872527396236]
adding 8 [0.9910323734014959, 0.9123549281413303]
adding 9 [0.9471174769069746, 0.13324391242530798]
adding 10 [0.34368411127047893, 0.4803022472664801]
adding 11 [0.3973344362253063, 0.013697542700323417]
adding 12 [0.04891968420549486, 0.18512952356979562]
adding 13 [0.5255249712817147, 0.2681324714369647]
adding 14 [0.08841648470140351, 0.10045458891458559]
adding 15 [0.9910167749095551, 0.6949953001955277]
adding 16 [0.10824545758198034, 0.5796720287967574]
adding 17 [0.7307476136117299, 0.7046505346722584]
adding 18 [0.22342087589891269, 0.953136638602066]
adding 19 [0.12823076336371653, 0.6325227106342147]
adding 20 [0.8038888407292407, 0.5813456531333389]
adding 21 [0.89960765466175, 0.3793073139560945]
adding 22 [0.4768371818738736, 0.9221889811494447]
adding 23 [0.3385434947123175, 0.6258185197900775]
adding 24 [0.2817284418659597, 0.22682901826571544]
adding 25 [0.5718627191729764, 0.936432768498482]
adding 26 [0.3449126951667061, 0.907322763836845]
adding 27 [0.9961967994454823, 0.8893837919258071]
adding 28 [0.7324204589213128, 0.515227662702998]
adding 29 [0.649925570866669, 0.5686119974920983]
adding 30 [0.6143335781128718, 0.4720201191941794]
adding 31 [0.6483752543659126, 0.6065798554820226]
adding 32 [0.06514621195402426, 0.24056326702027664]
kdtree size 33
removing 0 [0.40248566366484806, 0.08038370892978197]
removing 1 [0.5965601809348549, 0.2193245804838001]
removing 2 [0.28369059130373764, 0.7106102236811087]
removing 3 [0.46108817320691575, 0.15265269640601276]
removing 4 [0.8747810784358925, 0.7066240720855618]
removing 5 [0.4832571563375021, 0.5772091371337079]
thread 'main' panicked at 'assertion failed: kdtree.remove(e, i) == 1', src/bin/kiddo_bug.rs:18:9
```

**Comment by wentasah** [comment]
This looks similar to #12. It seems that the fix (#14) is incorrect or insufficient. I'm looking into it.

**Comment by wentasah** [comment]
I've [extended the test for #12](https://github.com/wentasah/kiddo/commit/a7779d7d2bf832faffbbce24530d399f9af81218) to cover also this issue. The test checked for removal of point 0 only. In my version, I try to remove all points, and the test fails on point 21.

**Comment by sdd** [comment]
Thanks for reporting - I'll see if I can get to the bottom of the problem.

**Comment by sdd** [comment]
Out of interest, what is the use case for the removal of the points? I must admit, `remove()` is a method that I don't use very often as I tend to frequently create a new tree from scratch instead, and perhaps that might work in your case. Of course I'll still fix this issue though either way! :-) 

I'm especially curious to understand the use cases behind people using `remove()` as, like you noticed, this is the second time that a bug in `remove()` has been spotted recently, so if the method is being used more frequently than I anticipated, then I can make sure that it gets enough attention in the future.

**Comment by wentasah** [comment]
I'm not sure how relevant my use cases are. I have a set of points and I need to deal with points which are close.

In one case, I simply need to remove them. Close enough points in noisy data represent a single canonical point. In my data set, there is just a few such points so it is faster to remove them, instead of rebuilding from scratch. But rebuilding from scratch after removing all needed points would work too.

In another use case, I need to move points, which are close, further away. I need to ensure a given minimum inter-point distance between all points. So I iterate the points and if one is close, I remove it, move somewhere else and add again. In this case, rebuilding from scratch would be expensive, because it would have to be done after every move.

**Comment by sdd** [comment]
Thanks - the use cases weren't relevant to the bug, I was just interested to hear how people use the library.

The bug was due to an issue when splitting full nodes whilst adding items to the tree. Previously it was possible for an item to end up in the wrong child bucket if there was more than one item in the bucket whose position in the dimension that the split is made on is the same as another item in the same bucket.

This was fixed in  https://github.com/sdd/kiddo/pull/29, and released as https://crates.io/crates/kiddo/2.0.2

**Comment by wentasah** [comment]
Thanks for quick fix. I confirm that with 2.0.2, I don't see any issue with removing points from my big dataset.
